name: matthandus-civicrm
recipe: drupal9
config:
  webroot: web
  xdebug: debug
  config:
    php: .vscode/php.ini
proxy:
  appserver:
    - matthandus-civicrm.lndo.site
    - matthandus-civicrm-2.lndo.site
    - matthandus-civicrm-3.lndo.site
  mail:
    - mail.matthandus-civicrm.lndo.site
services:
  appserver:
    build_as_root:
      - pecl install uploadprogress
      - docker-php-ext-enable uploadprogress
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - npm install --global yarn gulp@^4.0.2
    build:
      - composer install
      - drush --root=/app/web sql-drop -y
      - npm install -y
      - yarn install --non-interactive --cwd /app/web/core
      - drush --root=/app/web si --db-url=mysql://drupal9:drupal9@database/drupal9 -y
      - cv core:install -f --cms-base-url="https://matthandus-civicrm.lndo.site/" --db=mysql://drupal9:drupal9@database/drupal9
      - drush --root=/app/web theme:enable civics
      - drush --root=/app/web config:set system.theme default civics -y
      - gulp init
    run:
      - gulp watch
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://matthandus-civicrm.lndo.site"
        SIMPLETEST_BASE_URL: "https://matthandus-civicrm.lndo.site/"
        SIMPLETEST_DB: "sqlite://localhost/tmp/db.sqlite"
        BROWSERTEST_OUTPUT_DIRECTORY: '/app/web/sites/simpletest/browser_output'
        BROWSERTEST_OUTPUT_BASE_URL: 'https://matthandus-civicrm.lndo.site'
        MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--ignore-certificate-errors", "--disable-gpu", "--headless", "--no-sandbox"]}}, "http://chrome:9515"]'
        # Nightwatch
        DRUPAL_TEST_BASE_URL: "https://matthandus-civicrm.lndo.site/"
        DRUPAL_TEST_DB_URL: 'mysql://drupal9:drupal9@database:3306/drupal9'
        DRUPAL_TEST_WEBDRIVER_HOSTNAME: chrome
        DRUPAL_TEST_WEBDRIVER_PORT: 9515
        DRUPAL_TEST_CHROMEDRIVER_AUTOSTART: 'false'
        DRUPAL_TEST_WEBDRIVER_CHROME_ARGS: "--ignore-certificate-errors --disable-gpu --headless --no-sandbox"
        DRUPAL_NIGHTWATCH_OUTPUT: reports/nightwatch
        DRUPAL_NIGHTWATCH_IGNORE_DIRECTORIES: node_modules,vendor,.*,sites/*/files,sites/*/private,sites/simpletest
  chrome:
    type: compose
    app_mount: false
    services:
      image: drupalci/webdriver-chromedriver:production
      command: chromedriver --log-path=/tmp/chromedriver.log --allowed-origins=* --verbose --whitelisted-ips=
  mail:
    type: mailhog
    hogfrom:
      - appserver
events:
  pre-start:
    - mkdir -p private/browsertest_output
    - touch private/xdebug.log
tooling:
  # Front-end tooling
  npm:
    service: appserver
  node:
    service: appserver
  gulp:
    service: appserver
  yarn:
    service: appserver
  # Back-end tooling
  drush:
    service: appserver
  phpunit:
    service: appserver
    user: www-data
    cmd:
      - appserver: php /app/vendor/bin/phpunit -c /app/phpunit.xml
  nightwatch:
    service: appserver
    description: Run Nightwatch.js
    cmd:
      - appserver: yarn test:nightwatch
    dir: /app/web/core
  # PHP Codesniffer
  phpcs:
    service: appserver
    cmd: "/app/vendor/bin/phpcs --standard=Drupal,DrupalPractice"
  phpcbf:
    service: appserver
    cmd: "/app/vendor/bin/phpcbf --standard=Drupal,DrupalPractice"
  # Twig Codesniffer
  twigcs:
    service: appserver
    cmd: "/app/vendor/friendsoftwig/twigcs"
