name: matthandus-civicrm
recipe: drupal9
config:
  webroot: web
  xdebug: debug
  config:
    php: .vscode/php.ini
services:
  appserver:
    build:
      - composer install
  node:
    type: node
    globals:
      gulp: latest
tooling:
  # Front-end tooling
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  # Back-end tooling
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "https://matthandus-civicrm.lndo.site"
